# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 11:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taxon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 28, 11, 24, 29, 134233, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
