# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoterequestformpage',
            old_name='side_panel',
            new_name='side_panel_content',
        ),
        migrations.AddField(
            model_name='quoterequestformpage',
            name='side_panel_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
