# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0001_initial'),
        ('quote', '0002_auto_20160615_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequestformpage',
            name='thank_you_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='formbuilder.FormThankYouPage'),
        ),
    ]
