# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_quoterequestformpage_thank_you_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequestformpage',
            name='success_message',
            field=models.CharField(default="Thanks, we'll get back to you shortly", max_length=255),
            preserve_default=False,
        ),
    ]
