# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_quoterequestformpage_success_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequestformpage',
            name='from_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='from address'),
        ),
        migrations.AlterField(
            model_name='quoterequestformpage',
            name='subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='quoterequestformpage',
            name='to_address',
            field=models.CharField(blank=True, help_text='Optional - form submissions will be emailed to this address', max_length=255, verbose_name='to address'),
        ),
    ]
