# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0006_auto_20160616_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequestformpage',
            name='from_address',
            field=models.EmailField(help_text='Form submissions will show as having come from this address', max_length=255),
        ),
        migrations.AlterField(
            model_name='quoterequestformpage',
            name='to_address',
            field=models.EmailField(help_text='Form submissions will be emailed to this address', max_length=255),
        ),
    ]
