# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 14:16
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20160520_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='pricing_footer',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
