# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_pricing_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_organisation', models.CharField(blank=True, max_length=100)),
                ('testimonial', models.TextField()),
            ],
        ),
    ]
