# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='customer_job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
