# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('home', '0012_peoplepage_peoplepageperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone_uri', models.CharField(blank=True, max_length=20)),
                ('phone_display', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('github_username', models.CharField(blank=True, max_length=255)),
                ('twitter_username', models.CharField(blank=True, max_length=15)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='peoplepageperson',
            name='team',
            field=models.CharField(choices=[('technical_team', 'Technical Team'), ('management_team', 'Management Team'), ('management_group', 'Management Group'), ('external_advisory', 'External Advisory Board')], default='technical_team', max_length=255),
            preserve_default=False,
        ),
    ]
