# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20160525_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsettings',
            name='address_uri',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='phone_uri',
            field=models.URLField(blank=True),
        ),
    ]
