# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_peoplepageperson_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplepageperson',
            name='role',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
