# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20160527_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplepageperson',
            name='short_bio',
            field=models.TextField(blank=True),
        ),
    ]
