# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20160601_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='thank_you_title',
            field=models.CharField(default='Thank you', max_length=255),
            preserve_default=False,
        ),
    ]
