# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('home', '0022_auto_20160608_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormThankYouPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('message', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameField(
            model_name='formpage',
            old_name='thank_you_title',
            new_name='success_message',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='thank_you_text',
        ),
        migrations.AddField(
            model_name='formpage',
            name='thank_you_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.FormThankYouPage'),
        ),
    ]
