# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20160616_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='side_panel_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
