# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailcore', '0028_merge'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('home', '0025_auto_20160616_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='page',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='thank_you_page',
        ),
        migrations.RemoveField(
            model_name='formthankyoupage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
        migrations.DeleteModel(
            name='FormPage',
        ),
        migrations.DeleteModel(
            name='FormThankYouPage',
        ),
    ]
