# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-23 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailcore', '0028_merge'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('home', '0026_auto_20160616_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='NewsPage',
        ),
    ]
