# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_testimonial_customer_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprice',
            name='body',
            field=models.TextField(),
        ),
    ]
