# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20160525_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsettings',
            name='address',
            field=models.TextField(),
        ),
    ]
