# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20160525_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplepageperson',
            name='role',
            field=models.CharField(default='Programmer', max_length=255),
            preserve_default=False,
        ),
    ]
