# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20160527_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplepageperson',
            name='organisation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
