# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_formpage_thank_you_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsettings',
            name='company_name',
            field=models.CharField(default='MicrobesNG', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='navigationmenuitem',
            name='menu_title',
            field=models.CharField(blank=True, help_text='Optional link titlein this menu (defaults to page title if one exists)', max_length=255),
        ),
    ]
