# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso2', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
