# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 11:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='id',
        ),
        migrations.AddField(
            model_name='country',
            name='iso3',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='phone_country_code',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='phone_trunk_code',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 28, 11, 10, 42, 820049, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='iso2',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
