# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-28 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueLink',
            fields=[
                ('quote_code', models.CharField(max_length=10)),
                ('unique_link', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
