# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-09-02 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquelink',
            name='xero_contact_id',
            field=models.UUIDField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='uniquelink',
            name='xero_invoice_id',
            field=models.UUIDField(default=None, null=True),
        ),
    ]
